### ISSUE TITLE
Web analytics service

### ISSUE THREAD

**Issue by ogajduse** [spacewalkproject/spacewalkproject.github.io#10]
We should be using some service to track visitor traffic.
I can see that [The Foreman](https://theforeman.org/) and [Kubernetes](https://kubernetes.io/), [Hawkular](http://www.hawkular.org/), [PatternFly](https://www.patternfly.org/) and [ManageIQ](http://manageiq.org/) project pages are using Google Analytics. There should be implemented something similar in Spacewalk web pages.

**Comment by jiridostal** [comment]
As we are running this site on Github pages, there is native traffic tracking.
