### ISSUE TITLE
Duplicated navbar 

### ISSUE THREAD

**Issue by sarkaaa** [spacewalkproject/spacewalkproject.github.io#12]
If the visitor views the FAQ category on website via his smartphone, there is duplicated navbar. I think it should be problem of Jekyll. I haven't investigated it yet.

![issue](https://user-images.githubusercontent.com/19727168/34160828-c6719428-e4ce-11e7-998b-b32e66a4de07.png)

**Comment by jiridostal** [comment]
d52a1292093951d22cb3bd9d219c766011de4aa4
